---
title: "Participan en esta edición del seminario"
format: html
toc: false
include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

---

```{r obtener-datos-participantes}
#| echo: false
#| warning: false
#| message: false

source("R/utils.R")

# Desactivar autenticación para spreadsheets públicos
gs4_deauth()

# Leer datos del Google Spreadsheet
url_hoja <- "https://docs.google.com/spreadsheets/d/10CI16PtJPUO5M_sz1bMJeDuIj4QN9phG-DRlhqD51C0/edit?usp=sharing"
datos_participantes <- read_sheet(url_hoja, sheet = "info-ponentes-sitio-web")

# Procesar los datos
datos_participantes <- datos_participantes |>
  mutate(
    # Si foto está vacía, usar default-avatar.svg, si no, agregar la ruta
    foto_path = ifelse(
      is.na(foto) | foto == "", 
      "img/participantes/default-avatar.svg",
      paste0("img/participantes/", foto)
    ),
    # Reemplazar NA en bio con string vacío
    bio = ifelse(is.na(bio), "", bio),
    # Reemplazar NA en nombre con string vacío
    nombre = ifelse(is.na(nombre), "", nombre)
  )
```


<br>

## Charla plenaria internacional

```{r render-keynote-internacional}
#| echo: false
#| warning: false
#| message: false 
#| results: asis

html_participantes_keynote_int <- datos_participantes |> 
  filter(tipo == "keynote-internacional") |> 
  rowwise() |>
  mutate(html = generar_div_presentador(foto_path, nombre, bio)) |>
  pull(html) |> 
  paste(collapse = "\n\n")

cat(html_participantes_keynote_int)
```

<br>

## Charla plenaria nacional

```{r render-keynote-nacional}
#| echo: false
#| warning: false
#| message: false 
#| results: asis

html_participantes_keynote_nac <- datos_participantes |> 
  filter(tipo == "keynote-nacional") |> 
  rowwise() |>
  mutate(html = generar_div_presentador(foto_path, nombre, bio)) |>
  pull(html) |> 
  paste(collapse = "\n\n")

cat(html_participantes_keynote_nac)
```

<br>

## Mesas de discusión (jueves)

```{r render-mesas}
#| echo: false
#| warning: false
#| message: false
#| results: asis

html_participantes_mesas <- datos_participantes |> 
  filter(tipo == "mesa temática jueves") |> 
  rowwise() |>
  mutate(html = generar_div_presentador(foto_path, nombre, bio)) |>
  pull(html) |> 
  paste(collapse = "\n\n")

cat(html_participantes_mesas)
```


## Pósteres (jueves)

```{r render-posters}
#| echo: false
#| warning: false
#| message: false
#| results: asis

html_participantes_posters <- datos_participantes |> 
  filter(tipo == "posters") |> 
  rowwise() |>
  mutate(html = generar_div_presentador(foto_path, nombre, bio)) |>
  pull(html) |> 
  paste(collapse = "\n\n")

cat(html_participantes_posters)
```

## Panel de fracasos (jueves)

```{r render-fracasos}
#| echo: false
#| warning: false
#| message: false
#| results: asis

html_participantes_fracasos <- datos_participantes |> 
  filter(tipo == "panel de fracasos") |> 
  rowwise() |>
  mutate(html = generar_div_presentador(foto_path, nombre, bio)) |>
  pull(html) |> 
  paste(collapse = "\n\n")

cat(html_participantes_fracasos)
```

## Charlas relámpago (jueves y viernes)

```{r render-relampago}
#| echo: false
#| warning: false
#| message: false
#| results: asis

html_participantes_relampago <- datos_participantes |> 
  filter(tipo == "charlas relámpago") |> 
  rowwise() |>
  mutate(html = generar_div_presentador(foto_path, nombre, bio)) |>
  pull(html) |> 
  paste(collapse = "\n\n")

cat(html_participantes_relampago)
```

## Workshops


```{r render-workshops}
#| echo: false
#| warning: false
#| message: false
#| results: asis

html_participantes_workshops <- datos_participantes |> 
  filter(tipo == "workshops") |> 
  rowwise() |>
  mutate(html = generar_div_presentador(foto_path, nombre, bio)) |>
  pull(html) |> 
  paste(collapse = "\n\n")

cat(html_participantes_workshops)
```


## Paneles temáticos (viernes)

```{r render-paneles}
#| echo: false
#| warning: false
#| message: false
#| results: asis

html_participantes_paneles <- datos_participantes |> 
  filter(tipo == "paneles temáticos") |> 
  rowwise() |>
  mutate(html = generar_div_presentador(foto_path, nombre, bio)) |>
  pull(html) |> 
  paste(collapse = "\n\n")

cat(html_participantes_paneles)
```

