---
title: "Programa"
format: html
toc: false
include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

---

Para conocer en qué consisten los distintos tipos de actividades, puedes revisar la sección ["Acerca del programa"](acerca-de.qmd).
<!--<br>
<br>
<span style="color: white; background-color: #8c52ff; padding: 6px 6px; font-size: 1.5rem;">
  ..:: horarios provisorios | sujetos a cambio ::..
</span>-->
<div class="nav-participantes">
  <a href="#jueves-9-de-abril-presencial" class="nav-programa-btn">Jueves 9 (presencial)</a>
  <a href="#viernes-10-de-abril-online" class="nav-programa-btn">Viernes 10 (online)</a>
</div>



```{r obtener-datos-programa}
#| echo: false
#| warning: false
#| message: false


source("R/utils.R")

# Desactivar autenticación para spreadsheets públicos
gs4_deauth()

# Leer datos del Google Spreadsheet
url_cronograma <- "https://docs.google.com/spreadsheets/d/1U1qjMhNzWZUzl4EK86YZpbPKhb9h16MaGRswCRPj2TI/edit?usp=sharing"
cronograma_jueves <- read_sheet(url_cronograma, sheet = "jueves-9")
cronograma_viernes <- read_sheet(url_cronograma, sheet = "viernes-10")



# Generar el HTML
html_jueves <- generar_html_cronograma(cronograma_jueves)
html_viernes <- generar_html_cronograma(cronograma_viernes)
```

# jueves 9 de abril (presencial)

Las actividades de este día se realizarán en el [Campus Lo Contador](https://maps.app.goo.gl/NFuyiH5Yqaehf3iW9) de la UC en los siguientes lugares:

- Edificio de Arquitectura:
    - Registro: Hall piso 1
    - Inauguración, Charla Magistral, Mesas A, C y E, Charlas relámpago: Auditorio piso 4 (Eduardo Castillo Velasco)
    - Exhibición de pósters: Terraza piso 4 
- Mesa B: Casa Sergio Larraín, piso 1
- Mesa D: Edificio Doctorado Arquitectura, piso 2
- Mesa F y Panel de Fracasos: Sala 17, también conocida como "La Piscina"

Revisa el [mapa  para la ubicación exacta dentro del campus](ubicacion.qmd).


```{=html}
`r html_jueves`
```

# viernes 10 de abril (online)

Las actividades de este día serán online a través de la plataforma Zoom. El enlace para conectarse se le enviará a las personas registradas vía correo electrónico. 

```{=html}
`r html_viernes`
```